### ISSUE TITLE
Verify that the replacement itself is valid?

### ISSUE THREAD

**Issue by joelmukuthu** [parshap/node-sanitize-filename#12]
I don't know why anyone would want to pass illegal/unsafe characters as the replacement but is it worthwhile to validate it?

**Comment by parshap** [comment]
That's a good thought. Users may not know what is invalid. It's not completely straight forward though. Take for example is someone sets the replacement to be `"."`. That string itself is not a valid filename, but it would work fine as a replacement for e.g., `"foo?.exe"` (which would then turn into `"foo..exe"`, which is valid). But then again, if the input was simply `"?"`, that replacement would result in the invalid filename `"."`.

I think this is worth protecting against, but it's not clear how. Maybe a two-pass approach:

```js
var input = "foo?.exe";
input = sanitize(input, { replacement: "." })
input = sanitize(someFileName, { replacement: "" });
```

**Comment by joelmukuthu** [comment]
Great insight! How about testing the output after sanitization and throwing an error if it's not valid? But then do we still throw an error if the output is just an empty string?
One way to resolve this is to stick to the premise that this module only sanitizes, it doesn't validate. In which case we'd run several passes until the filename is sanitized or just an empty string. I think this is the best way to resolve this and that it should be well documented so it doesn't end up being an unexpected result to someone using the module.

**Comment by parshap** [comment]
> One way to resolve this is to stick to the premise that this module only sanitizes, it doesn't validate. In which case we'd run several passes until the filename is sanitized or just an empty string. I think this is the best way to resolve this and that it should be well documented so it doesn't end up being an unexpected result to someone using the module.

This sounds right to me. I already have a section in the readme [about empty string results][empty] but it could probably be improved.

[empty]: https://github.com/parshap/node-sanitize-filename#empty-filenames

**Comment by joelmukuthu** [comment]
Oh right, I'd forgotten about the note in the readme. I think it covers this scenario sufficiently.
I've created a PR to address this, using your two-pass approach, please have a look!
