### ISSUE TITLE
./ at the beginning of a file name produces a hidden file

### ISSUE THREAD

**Issue by adam-s** [parshap/node-sanitize-filename#15]
If a file name that is being sanitized begins with ./ ,the forward slash will be removed but the period will stay to create a hidden system file.

**Comment by parshap** [comment]
The scope of this module is to *coerce a string to be safe for use as a filename*. Filenames that begin with `.` are legal filenames and thus I think any further manipulation of the filename should happen outside of this module. For example: `sanitize(filename).replace(/^\.+/, "")`.

What do you think? Are you having any problem with files that begin with `.`?

**Comment by parshap** [comment]
Going to close this with the conclusion that *sanitize-filename* should do the minimum possible to guarantee safe filenames. Any further processing should be done by end users (or another module).

If anyone has problems with hidden files please re-open this issue.
