### ISSUE TITLE
Replace characters with similar

### ISSUE THREAD

**Issue by goatandsheep** [parshap/node-sanitize-filename#25]
Instead of removing all illegal characters. Some can be replaced by alternatives, for example:

* `* --> ∗`
* `' --> ＇`
* `" --> ＂`

Is this a good idea?

**Comment by parshap** [comment]
Clever idea! On one hand it makes the files look nicer, but on the other it makes it more difficult to know exactly what the filename is by looking at it. I guess it depends on the use case. I think I would be open to this as an option. I wonder what others think. /cc @joelmukuthu

**Comment by goatandsheep** [comment]
Maybe it would be an issue if you are using something that requires ascii.

**Comment by parshap** [comment]
We [don't support FAT filesystems](https://github.com/parshap/node-sanitize-filename#file-systems) so I don't think that will be an issue. Would you be interested in implementing this feature and sending a PR?

**Comment by goatandsheep** [comment]
sure

**Comment by joelmukuthu** [comment]
Sorry for replying late as I see this has already progressed, but it's a pretty interesting idea. @goatandsheep do you have a use case that this aims to solve?

**Comment by goatandsheep** [comment]
I have a use case, but it needs ascii, so after I did the PR, I did it differently

**Comment by parshap** [comment]
See https://github.com/parshap/node-sanitize-filename/pull/26
