### ISSUE TITLE
This library is insecure in practice

### ISSUE THREAD

**Issue by Rob--W** [parshap/node-sanitize-filename#4]
After seeing the name "sanitize-filename", I thought that the library was going to output a name that is considered to be safe (secure) for use a filename. After reviewing the code, I concluded otherwise.

For example, `..` is returned as `..`, which is not suitable for most I/O-related operations (imagine: creating a new "temporary" directory/file, then removing the temporary directory with rimraf. Oops, now you've lost much more than the temporary directory/file). Besides this obvious case, there are several other constraints outlined at https://msdn.microsoft.com/en-us/library/aa365247.aspx.

This could be fixed in several ways, including but not limited to:

- Return an empty string if the filename is insecure (then callers can use `sanitize(filename) || 'defaultname'` if they want to).
- Add a prefix / suffix if the filename is insecure.

**Comment by parshap** [comment]
Thanks for reviewing the implementation, @Rob--W.

I've made [a change to catch `.` and `..` filenames][change]. This is published as `sanitize-filename@1.1.2`.

Let me know what you think or if you see any other issues.

[change]: https://github.com/parshap/node-sanitize-filename/commit/4b2773b1adb6032efca295f3314b32f6e20d848a

**Comment by parshap** [comment]
Closing this issue as the problem with `.` and `..` has been resolved, but feel free to reopen if there's anything else. Thanks again!
