### ISSUE TITLE
please put comma character also for sanitization.

### ISSUE THREAD

**Issue by geekabhi** [parshap/node-sanitize-filename#42]
put comma in illegalRe to sanitize file name. It will be help full while setting the contentDisposition header with filename.

setHeader('Content-disposition', 'attachment;filename=' + sanitizedFileName);

**Comment by joelmukuthu** [comment]
Hi, sorry for the late reply but that’s out of scope for this module. I think the solution for that issue lies more along the lines of `encodeURIComponent`
