### ISSUE TITLE
Strict mode to throw on error?

### ISSUE THREAD

**Issue by oncletom** [parshap/node-sanitize-filename#43]
Hello,

This module is super useful :-)
I was wondering if you considered throwing an error if the path appeared to be invalid? Or to expose a function to validate if the path is safe?

Thank you for your answer :-)

**Comment by parshap** [comment]
Hi. I think you could implement this pretty easily yourself and it's not worth having it in the core library.

```js
const assert = require('assert');
const sanitize = require('sanitize-filename');

const assertSafeFilename = filename => assert.equal(
  filename,
  sanitize(filename),
  'Filename not safe'
);

module.exports = assertSafeFilename;

**Comment by oncletom** [comment]
Agreed. I was thinking about it being a convenience method.

I totally understand your point of view.

Thanks for your prompt reply 🙂
