### ISSUE TITLE
Not deleting dots

### ISSUE THREAD

**Issue by george-norris-salesforce** [parshap/node-sanitize-filename#53]
```
var sanitizeFilename = require("sanitize-filename")
sanitizeFilename('../test')
```
returns..
`"..test"`

In the README it says 
`sanitize-filename removes the following:     
 Unix reserved filenames (. and ..)`

Is the correct behavior?

**Comment by parshap** [comment]
Yes, that's correct behavior. The literal file names `.` and `..` are reserved, but if there's other characters then it's a valid file name. Here's an example:

```
$ echo 'hello' > ..test
$ cat ..test
hello
```

If you'd like cleaner filenames you could run it through something like [@sindresorhus/slugify](https://www.npmjs.com/package/@sindresorhus/slugify) in addition to sanitizing.
