### ISSUE TITLE
ES6 import/export syntax to use module

### ISSUE THREAD

**Issue by finn-matti** [parshap/node-sanitize-filename#64]
As the title suggests: It would be great if this was usable with the import/export syntax.

At least my IDE is complaining:

>import * as sanitize from 'sanitize-filename';

>This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

**Comment by joelmukuthu** [comment]
Hi @finn-matti, as the error from your IDE suggests, you need to add the `esModuleInterop` flag to your `tsconfig.json`:

```json5
{
  "compilerOptions": {
    "esModuleInterop": true
  }
}
```

and then import the module via it's default export:

```ts
import sanitize from "sanitize-filename";

const sanitized = sanitize(unsanitizedString);
```

**Comment by finn-matti** [comment]
@joelmukuthu … and restart the IDE, I guess, to make get it to work.
