### ISSUE TITLE
tests against the filesystem?

### ISSUE THREAD

**Issue by paulirish** [parshap/node-sanitize-filename#7]
Can you drop these in as filenames and verify they are never rejected?

**Comment by parshap** [comment]
Do you mean tests that call `fs.writeFile` and make sure there is no error? That sounds like a good idea.

**Comment by paulirish** [comment]
Yup!

**Comment by parshap** [comment]
Ok. I will try to get this in or will gladly accept a patch.

**Comment by parshap** [comment]
Published in 1.1.4. Thanks for the idea!

**Comment by parshap** [comment]
If you have any more test cases in mind other than [the file names that are currently there][names], I'd be happy to add them.

[names]: https://github.com/parshap/node-sanitize-filename/blob/28a2576fca7c03490e74ed5710385d3b9189d65a/test.js#L78-L91
